
######################## POMIAR PRĄDU I NAPIĘCIA ########################

- platform: ads
  name: Licznik główny gazu                 ## główna wartość licznika gazu
  adsvar: GVL_Gas.iGasMeter
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
  scan_interval: 1000

- platform: ads
  name: Licznik główny gazu zeszły miesiac  ## główna wartość licznika gazu
  adsvar: GVL_Gas.iGasMeterLastMonth
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
  scan_interval: 1000
  
- platform: ads
  name: Zużycie gazu w tym dniu             ## zużycie w danym dniu
  adsvar: GVL_Gas.iGasMeterUsedToday
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
  scan_interval: 1000

- platform: ads
  name: Zużycie gazu w tym miesiacu         ## zużycie w danym miesiącu
  adsvar: GVL_Gas.iGasMeterUsed
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
  scan_interval: 1000

- platform: ads
  name: Koszt gazu w tym miesiacu           ## koszt gazu w tym miesiącu
  adsvar: P_GasMeter.iCostOfEnergy
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int
  scan_interval: 1000

- platform: ads
  name: Licznik impulsów gaz PLC godzin   ## ilość impulsów w danej godzinie
  adsvar: P_GasMeter.iTrigerCountHour
  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Licznik impulsów gaz PLC dzien     ## ilość impulsów w danym dniu
  adsvar: P_GasMeter.iTrigerCount
  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Licznik impulsów gaz PLC miesiac   ## ilość impulsów w danym miesiacu
  adsvar: P_GasMeter.iTrigerCountMonth
  unit_of_measurement: 'impuls'
  adstype: int

- platform: ads
  name: Cena gazu                           ## aktualna cena za m3 gazu
  adsvar: P_GasMeter.iCostPerHour
  unit_of_measurement: 'zł/kWh'
  factor: 100
  adstype: int
  scan_interval: 100
