
######################## AKTYWNOŚĆ MULTIMEDIÓW ########################

- platform: template
  sensors:
    time_salon_tv:
      value_template: '{{ state_attr("remote.salon", "current_activity") }}'
      #friendly_name: 'Czas TV w salonie'
    time_media_player:
      value_template: '{{ state_attr("media_player.salon_music", "current_activity") }}'
      #friendly_name: 'Czas w salon music'

    harmony_activity:
      value_template: >
        {% if is_state("remote.harmony_hub", 'on') %}
          {{ states.remote.harmony_hub.attributes.current_activity }}
        {% else %}
          PowerOff
        {% endif %}
        
    salon_tv_activity:
      value_template: >
        {% if is_state("remote.salon", 'on') %}
          {{ states.remote.salon_tv.attributes.current_activity }}
        {% else %}
          PowerOff
        {% endif %}
         
    salon_music_activity:
      value_template: >
        {% if is_state("remote.salon_music", 'on') %}
          {{ states.remote.salon_music.attributes.current_activity }}
        {% else %}
          PowerOff
        {% endif %}
    speaker_volume:
      #icon: 'mdi:volume-high'
      value_template: "{{ state_attr('media_player.office_speaker', 'volume_level') | round(2) }}"
      friendly_name: 'Głośność GH w biurze:'
