
######################## TEMPERATURY POWIETRZA ########################

- platform: ads
  name: Temp. rozdzielnica P1
  adsvar: GVL_IO.iTemp_A12[1].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
  scan_interval: 1000
- platform: ads
  name: Temp. rozdzielnica P0
  adsvar: GVL_IO.iTemp_A2[1].bTemp
  unit_of_measurement: '°C'
  factor: 100 
  adstype: int
  scan_interval: 1000