
 ######################## CZASY ZAŁĄCZONYCH ELEMENTÓW ########################
 
 # UPS
- platform: history_stats
  name: ups time_on
  entity_id: binary_sensor.ping_plc
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# PLC
- platform: history_stats
  name: plc time_on
  entity_id: binary_sensor.ping_plc
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# FutroS920
- platform: history_stats
  name: futro_s920 time_on
  entity_id: binary_sensor.ping_futro_s920
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# SWITCH POE
- platform: history_stats
  name: switch_poe time_on
  entity_id: binary_sensor.ping_router
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# SWITCHES
- platform: history_stats
  name: switches time_on
  entity_id: binary_sensor.ping_router
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# ROUTER
- platform: history_stats
  name: Router time_on
  entity_id: binary_sensor.ping_router
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# SWITCH OD GBN
- platform: history_stats
  name: gbn_switch time_on
  entity_id: binary_sensor.ping_router
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO MONITOR 
- platform: history_stats
  name: Monitor Time_ON
  entity_id: switch.pantrymonitorpowersocket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO LAPTOPA 
- platform: history_stats
  name: Laptop Time_ON
  entity_id: switch.officelaptoppowersocket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Laptop Count_ON
  entity_id: switch.officelaptoppowersocket
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# GNIAZDKA BIURO
- platform: history_stats
  name: biuro time_on
  entity_id: switch.officepowersocket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: biuro count_on
  entity_id: switch.officepowersocket
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

 # GNIAZDKO LAPTOPA JULIA
- platform: history_stats
  name: Laptop Julia Time_ON
  entity_id: switch.julia_laptop
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Laptop Julia Count_ON
  entity_id: switch.julia_laptop
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# LODÓWKA
- platform: history_stats
  name: biuro time_on
  entity_id: switch.fridge_powersocket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: biuro count_on
  entity_id: switch.fridge_powersocket
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# BOILER CO
- platform: history_stats
  name: biuro time_on
  entity_id: switch.boiler_powersocket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: biuro count_on
  entity_id: switch.boiler_powersocket
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
  
# GNIAZDKA PRALKA
- platform: history_stats
  name: washing_machine time_on
  entity_id: sensor.pranie
  state: 'Trwa pranie...'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: washing_machine count_on
  entity_id: sensor.pranie
  state: 'Trwa pranie...'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
  
# DISKSTATION
- platform: history_stats
  name: Diskstation time_on
  entity_id: binary_sensor.ping_diskstation
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Diskstation count_on
  entity_id: binary_sensor.ping_diskstation
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'  

# GNIAZDKA SALON TV
- platform: history_stats
  name: salon_tv time_on
  entity_id: switch.gniazdka_tv_salon
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: salon_tv count_on
  entity_id: switch.gniazdka_tv_salon
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

# STRYCH, WZMACNIACZ ANTENOWY, KAMERA PIĘTRO
- platform: history_stats
  name: attic time_on
  entity_id: switch.gniazdka_strych
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: attic count_on
  entity_id: binary_sensor.ping_router
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

