
######################## POMIAR PRĄDU I NAPIĘCIA ########################

- platform: ads
  name: Licznik główny prądu                ## główna wartośćlicznika prądu
  adsvar: GVL_Power.iPowerMeter
  unit_of_measurement: 'kWh'
  factor: 100
  adstype: dint
  scan_interval: 1000

- platform: ads
  name: Licznik główny prądu zeszły miesiac ## główna wartość licznika prądu z zeszłego miesiąca
  adsvar: GVL_Power.iPowerMeterLastMonth
  unit_of_measurement: 'm³'
  factor: 100
  adstype: dint
  scan_interval: 1000
  
- platform: ads
  name: Koszt pradu w tym miesiącu          ## koszt prądu w tym miesiącu
  adsvar: P_PowerMeter.iCostOfEnergyDay
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int
  scan_interval: 1000

- platform: ads
  name: Koszt prądu miesieczny trend        ## trend kosztów prądu na ten miesiąc
  adsvar: P_PowerMeter.iCostOfEnergyTrend
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int
  scan_interval: 1000

- platform: ads
  name: Koszt pradu na godzine              ## bierzący koszt prądu wg aktualnego zużycia
  adsvar: P_PowerMeter.iCostOfEnergy
  unit_of_measurement: 'zł'
  factor: 100
  adstype: int
  scan_interval: 1000

- platform: ads
  name: Cena pradu                          ## aktualna cena za kWh prądu
  adsvar: P_PowerMeter.iCostPerHour
  unit_of_measurement: 'zł/kWh'
  factor: 100
  adstype: int
  scan_interval: 1000


######################## PODZIAŁ NA FAZY ########################

- platform: ads
  name: Voltage_L1
  adsvar: HomeAssistant.iVoltage_L1
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: Voltage_L2
  adsvar: HomeAssistant.iVoltage_L2
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: Voltage_L3
  adsvar: HomeAssistant.iVoltage_L3
  unit_of_measurement: 'V'
  factor: 10
  adstype: int
  scan_interval: 1000

- platform: ads
  name: iPower_L1
  adsvar: HomeAssistant.iPower_L1
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iPower_L2
  adsvar: HomeAssistant.iPower_L2
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iPower_L3
  adsvar: HomeAssistant.iPower_L3
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
  scan_interval: 1000

- platform: ads
  name: iCurrent_L1
  adsvar: HomeAssistant.iCurrent_L1
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iCurrent_L2
  adsvar: HomeAssistant.iCurrent_L2
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iCurrent_L3
  adsvar: HomeAssistant.iCurrent_L3
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
  scan_interval: 1000

- platform: ads
  name: iEnergy_L1
  adsvar: HomeAssistant.iEnergy_L1
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iEnergy_L2
  adsvar: HomeAssistant.iEnergy_L2
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iEnergy_L3
  adsvar: HomeAssistant.iEnergy_L3
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
  scan_interval: 1000
  
# - platform: ads
#   name: iPower_SUM_test
#   adsvar: HomeAssistant.iPower_SUM
#   unit_of_measurement: 'W'
#   #factor: 10
#   adstype: int
#   scan_interval: 1000
- platform: ads
  name: iPower_SUM
  adsvar: HomeAssistant.iPower_SUM
  unit_of_measurement: 'W'
  factor: 1
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iCurrent_SUM
  adsvar: HomeAssistant.iCurrent_SUM
  unit_of_measurement: 'A'
  factor: 10
  adstype: int
  scan_interval: 1000
- platform: ads
  name: iEnergy_SUM
  adsvar: HomeAssistant.iEnergy_SUM
  unit_of_measurement: 'kWh'
  factor: 10
  adstype: int
  scan_interval: 1000
