
######################## CZUJNIKI ANALOGOWE ########################

- platform: ads
  name: Natężenie światła
  adsvar: HomeAssistant.iNATEZENIE_SWIATLA
  unit_of_measurement: 'lux'
  factor: 1
  adstype: int

- platform: ads
  name: Siła wiatru
  adsvar: HomeAssistant.iSILA_WIATRU
  unit_of_measurement: 'km/h'
  factor: 10
  adstype: int

- platform: ads
  name: Temp. Zewnętrzna
  adsvar: HomeAssistant.iTemp_OUTSITE
  unit_of_measurement: '°C'
  factor: 10
  adstype: int
  scan_interval: 1000