
    ######################## SYSTEMOWE ########################
     
sensor:

##################### JAKOsĆ POWIETRZA ########################

    - platform: rest
      scan_interval: 900
      name: Airly
      resource: https://airapi.airly.eu/v2/measurements/nearest?lat=50.1419817789&lng=18.9935025573&maxDistanceKM=5
      value_template: "{{ value_json['current']['values'][0]['value'] }} {{ value_json['current']['values'][1]['value'] }} {{ value_json['current']['values'][2]['value'] }} {{ value_json['current']['values'][3]['value'] }} {{ value_json['current']['values'][4]['value'] }} {{ value_json['current']['values'][5]['value'] }} {{ value_json['current']['indexes'][0]['level'] }} {{ value_json['current']['indexes'][0]['value'] }} {{ value_json['current']['indexes'][0]['description'] }}"
      headers:
        apikey: !secret airly_api
        Accept-Language: pl 
          
    - platform: template
      sensors:
        airly_pm1:
          friendly_name: "Pyl PM1"
          icon_template: mdi:jquery
          unit_of_measurement: "μg/m3"
          value_template: "{{ states.sensor.airly.state.split(' ')[0] }}"
        airly_pm25:
          friendly_name: "Pyl PM25"
          icon_template: mdi:jquery
          unit_of_measurement: "μg/m3"
          value_template: "{{ states.sensor.airly.state.split(' ')[1] }}"
        airly_pm10:
          friendly_name: "Pyl PM10"
          icon_template: mdi:jquery
          unit_of_measurement: "μg/m3"
          value_template: "{{ states.sensor.airly.state.split(' ')[2] }}"
        airly_pressure:
          friendly_name: "Cisnienie"
          icon_template: mdi:gauge
          unit_of_measurement: "hPA"
          value_template: "{{ states.sensor.airly.state.split(' ')[3] | float(0)| round(1) }}"
        airly_humidity:
          friendly_name: "Wilgotnosć"
          icon_template: mdi:water-percent
          unit_of_measurement: "%"
          value_template: "{{ states.sensor.airly.state.split(' ')[4] | float(0)| round(0) }}"
        airly_temperature:
          friendly_name: "Temperatura"
          icon_template: mdi:thermometer
          unit_of_measurement: "°C"
          value_template: "{{ states.sensor.airly.state.split(' ')[5] | float(0)| round(1) }}"
        airly_quality:
          friendly_name: "Jakosć powietrza"
          icon_template: mdi:quicktime
          value_template: "{{ states.sensor.airly.state.split(' ')[6] }}"
        airly_level:
          friendly_name: "Poziom"
          icon_template: mdi:database
          value_template: "{{ states.sensor.airly.state.split(' ')[7] | float(0)| round(0) }}"
        airly_description:
          friendly_name: "Komunikat"
          icon_template: mdi:alert
          value_template: "{{ states.sensor.airly.state.split(' ')[8:] | join(' ') }}"
 