---
# https://community.home-assistant.io/t/update-notifications-core-hacs-supervisor-and-addons/182295

######################################## SYSTEM SENSORS ########################################

automation:

  - alias: Updates Pending
    id: 29168124-d520-4d81-a867-e4ca453f0320
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.updater_core
      - platform: state
        entity_id: sensor.updater_hassos
      - platform: state
        entity_id: sensor.updater_supervisor
      - platform: state
        entity_id: sensor.hacs
      - platform: homeassistant
        event: start
    action:
      - alias: "Update Persistent Notification"
        choose:
          conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ states('sensor.updater_core') == 'on' }}"
              - condition: template
                value_template: "{{ states('sensor.updater_hassos') == 'on' }}"
              - condition: template
                value_template: "{{ (states('sensor.updater_supervisor') | float) != 0 }}"
              - condition: template
                value_template: "{{ (states('sensor.hacs') | float) != 0 }}"
          sequence:
          - service: persistent_notification.create
            data_template:
              title: Updates Pending
              message: |
                {% set core_entity_id = 'sensor.updater_core' %}
                {% set os_entity_id = 'sensor.updater_hassos' %}
                {% if states(core_entity_id) == 'on' or states(os_entity_id) == 'on' %}
                [Home Assistant](/hassio/dashboard)
                  {% if states(core_entity_id) == 'on' %}
                * **Core** {{ state_attr(core_entity_id,"current_version") }} -> {{ state_attr(core_entity_id,"newest_version") }}  [`PRE-CHECK LOG`](/hassio/addon/core_check_config/logs)
                  {% endif %}
                  {% if states(os_entity_id) == 'on' %}
                * **OS** {{ state_attr(os_entity_id,"current_version") }} -> {{ state_attr(os_entity_id,"newest_version") }}
                  {% endif %}
                {% endif %}

                {% set supervisor_entity_id = 'sensor.updater_supervisor' %}
                {% if (states(supervisor_entity_id) | float) != 0 %}
                [Add-ons](/hassio/dashboard)
                  {% for addon in state_attr(supervisor_entity_id, 'addons') %}
                * [**{{ addon.name }}**](/hassio/addon/{{ addon["slug"] }}/info) {{ addon["version"] }} -> {{ addon["version_latest"] }}
                  {% endfor %}
                {% endif %}

                {% set hacs_entity_id = 'sensor.hacs' %}
                {% if (states(hacs_entity_id) | float) != 0 %}
                [HACS](/hacs/entry)
                  {% for repo in state_attr(hacs_entity_id, 'repositories') %}
                * **{{ repo.display_name }}** {{ repo["installed_version"] }} -> {{ repo["available_version"] }}
                  {% endfor %}
                {% endif %}
                
              notification_id: "updates_pending"
        default:
          - service: persistent_notification.dismiss
            data:
              notification_id: "updates_pending"

  - alias: Check Home Assistant Configuration
    id: 29168124-d520-4d81-a867-e4ca453f03
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.updater_core
        to: 'on'
    action:
      - service: hassio.addon_start
        data:
          addon: core_check_config
