
    ######################## SYSTEMOWE ########################
     
sensor:

    ######################## POWIADOMIENIE O LOGOWANIU########################
    
    - platform: authenticated

    ######################## SYSTEMOWE ########################
    
    - platform: version
      name: Installed Version
      source: local
        
    - platform: version
      name: Latest Available Version
      beta: false
      image: default 
      source: hassio
    
    - platform: uptime
    
    - platform: dnsip
    - platform: dnsip
      hostname: home-assistant.io
      name: hass
      resolver: 8.8.8.8
        
    ######################## SYSTEM DATA I CZAS ########################
    
    - platform: time_date
      display_options:
        - 'time'
        - 'date'
        - 'date_time'
        - 'time_date'
        - 'beat'
    
    ######################## BLOK DANYCH DB ########################
    
    - platform: filesize
      file_paths:
        - /config/home-assistant_v2.db
        - /config/home-assistant.log
    
    
    - platform: sql
      db_url: !secret mariadb
      queries:
        - name: 'DataBase rozmiar'
          query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
          column: 'value'
          unit_of_measurement: MB
    
