
    ######################## SYSTEMOWE ########################
     
sensor:

    ######################## ODKURZACZ ########################
    
    - platform: template
      sensors:
        vacuum_status:
          friendly_name: Status
          value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
          icon_template: >
           {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
            {% if val == 'Charging' %}
              mdi:battery-charging
            {% elif val == 'Cleaning' %}
              mdi:move-resize
            {% elif val == 'Returning home' %}
              mdi:keyboard-return
            {% elif val == 'Idle' %}
              mdi:dots-horizontal
            {% elif val == 'Paused' %}
              mdi:pause-circle
            {% else %}
              mdi:help-circle
            {% endif %}
        vacuum_fan_speed:
          friendly_name: Fan Speed
          value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
          icon_template: 'mdi:speedometer'
        vacuum_battery:
          friendly_name: Vacuum Battery
          value_template: 'Bateria: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
          unit_of_measurement: '%'
          icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'
        vacuum_cleaning_time:
          friendly_name: Time of Last Cycle
          value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time   }}'
          icon_template: 'mdi:timer'
        vacuum_cleaned_area:
          friendly_name: Area of Last Cycle
          unit_of_measurement: 'm ²'
          value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area   }}'
          icon_template: 'mdi:ruler'
        vacuum_cleanmainbrush:
          friendly_name: Replace main brush
          unit_of_measurement: 'h'
          value_template: 'Glowna szczotka: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left  }}'
          icon_template: 'mdi:screwdriver'
        vacuum_cleansidebrush:
          friendly_name: Replace side brush
          unit_of_measurement: 'h'
          value_template: 'Boczna szczotka: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left  }}'
          icon_template: 'mdi:screwdriver'
        vacuum_cleanfilter:
          friendly_name: Replace filter
          unit_of_measurement: 'h'
          value_template: 'Filtr: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left   }}'
          icon_template: 'mdi:screwdriver'
        vacuum_sensordirtyleft:
          friendly_name: Replace mop
          unit_of_measurement: 'h'
          value_template: 'Czujnik: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left  }}'
          icon_template: 'mdi:screwdriver'
