- id: '1640780140257'
  alias: Uruchomienie HA
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.startup_ha
      - input_boolean.uruchamianie
    data: {}
  mode: single

