
######################## ZAWORY WODY ########################

- platform: ads
  name: Zawor wody 1 otwórz
  adsvar: P_BOILER.bOpenValve1
- platform: ads
  name: Zawor wody 1 zamknij
  adsvar: P_BOILER.bCloseValve1

- platform: ads
  name: Zawor wody 2 otwórz
  adsvar: P_BOILER.bOpenValve2
- platform: ads
  name: Zawor wody 2 zamknij
  adsvar: P_BOILER.bCloseValve2

- platform: ads
  name: Zawor wody 3 otwórz
  adsvar: P_BOILER.bOpenValve3
- platform: ads
  name: Zawor wody 3 zamknij
  adsvar: P_BOILER.bCloseValve3

- platform: ads
  name: Reset czujnikow zalania
  adsvar: P_BOILER.b_water_sensor_reset

- platform: ads
  name: Pompa cyrkulacji wymuszenie
  adsvar: P_BOILER.bBridgePomp

- platform: ads
  name: Mostek czujnikow zalania
  adsvar: P_BOILER.bWaterSensorBridge