
################## COVER TEMPLATE ################## 

- platform: template
  covers:

################## BRAMA WJAZDOWA ################## 

    entrance_gate:
      device_class: gate
      friendly_name: "Entrance gate"
      value_template: "{{ is_state('binary_sensor.entrance_gate_closed', 'off')}}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_wjazdowa_otworz
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_wjazdowa_zamknij
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_wjazdowa_sbs
      icon_template: >-
        {% if is_state("binary_sensor.entrance_gate_closed", "on") %}
          mdi:gate
        {% else %}
           {% if is_state("binary_sensor.entrance_gate_opened", "on") %}
            mdi:gate-open
         {% else %}
           mdi:gate-arrow-right
         {% endif %}
        {% endif %}

################## BRAMA GARAŻOWA ################## 

    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_closed', 'off')}}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_garazowa_otworz
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_garazowa_zamknij
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.brama_garazowa_sbs
      icon_template: >-
        {% if is_state("binary_sensor.garage_closed", "on") %}
          mdi:garage-variant
        {% else %}
           {% if is_state("binary_sensor.garage_opened", "on") %}
            mdi:garage-open-variant
         {% else %}
           mdi:garage-alert-variant
         {% endif %}
        {% endif %}

    