
######################## BURZE.NET ########################

- platform: burze_dzis_net
  api_key: !secret burzedzis_net
  warnings:
   - frost_warning
   - heat_warning
   - wind_warning
   - precipitation_warning
   - storm_warning
   - tornado_warning
  storms_nearby:
    radius: 20
