
######################## CZUJNIKI DRZWI PARTER ########################

- platform: ads
  name: doors_all
  device_class: door
  adsvar: GVL_Sensors.bDOOR_SENSOR_ALL_P0

- platform: ads
  name: door_boiler
  device_class: door
  adsvar: GVL_Sensors.bDOOR_SENSOR_BOILER_EXIT
- platform: ads
  name: door_entrance
  device_class: door
  adsvar: GVL_Sensors.bDOOR_SENSOR_ENTRANCEHALL_EXIT
