
######################## CZUJNIKI RUCHU PARTER ########################

- platform: ads
  name: move_hall_down
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_ENTRENCE_HALL_DWN
- platform: ads
  name: move_entrance
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_ENTRENCE_EXIT
- platform: ads
  name: move_boiler
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_BOILER
- platform: ads
  name: move_garage
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_GARAGE
- platform: ads
  name: move_smallroom
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_SMALLROOM
- platform: ads
  name: move_kitchen
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_KITCHEN
- platform: ads
  name: move_salon
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_SALON
- platform: ads
  name: move_bathroom_down
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_BATHROOM_DOWN
- platform: ads
  name: move_weardrobe_entrance
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_ENTRENCE_WEAR
- platform: ads
  name: move_pantry
  device_class: motion
  adsvar: GVL_Sensors.bMOVE_SENSOR_PANTRY 

######################## CZUJNIKI RUCHU PIĘTRO ########################

- platform: ads
  name: move_hall_up
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_ENTRENCE_HALL_UP
- platform: ads
  name: move_oliwia
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_OLIWIA_ROOM
- platform: ads
  name: move_julia
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_JULIA_ROOM
- platform: ads
  name: move_bathroom_up
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_BATHROOM_UP
- platform: ads
  name: move_badroom
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_BADROOM
- platform: ads
  name: move_weardrobe_badroom
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_BADROOM_WEAR
- platform: ads
  name: move_washroom
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_WASHROOM
- platform: ads
  name: move_office
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_OFFICE

######################## CZUJNIKI RUCHU STRYCH ########################

- platform: ads
  name: move_attic
  device_class: motion
  adsvar: GVL_SENSORS.bMOVE_SENSOR_ATTIC

######################## CZUJNIKI OCZEKIWANIA NA RUCH W KUCHNI ########################

- platform: ads
  name: move_waiting_morning
  device_class: motion
  adsvar: P_BLINDS.bSunWaiting

