
######################## ZEZWOLENIE NA URUCHOMIENIE GNIAZDEK ########################

- platform: ads
  name: Zezwolenie na media parter
  device_class: motion
  adsvar: P_Power_socket_p0.bRelease
  
- platform: ads
  name: Zezwolenie na media pietro
  device_class: power
  adsvar: P_Power_socket_p1.bRelease
