
######################## SYSTEMOWE ########################

- platform: ads
  name: AlwaysTrue
  adsvar: GVL.bTrue

- platform: ads
  name: Ring_button
  adsvar: HomeAssistant.bDzwonek_Przycisk

- platform: ads
  name: Slonce_full
  adsvar: P_System.bSlonecznie
  device_class: light  

- platform: ads
  name: Brak wiatru 60m
  adsvar: P_System.bBrakWiatru_60m
- platform: ads
  name: Brak wiatru 10m
  adsvar: P_System.bBrakWiatru_10m
- platform: ads
  name: Brak wiatru 2m
  adsvar: P_System.bBrakWiatru_2m

- platform: ads
  name: LifeBitPLC
  adsvar: P_SYSTEM.bLifeBit
    
- platform: ads
  name: LifeBitPLC HA
  adsvar: P_SYSTEM.bLifeBitHA
- platform: ads
  name: LifeBitPLC HA error
  adsvar: P_SYSTEM.bLifeBitHAerror

- platform: ads
  name: Testowy bool 1
  adsvar: P_SYSTEM.bTestowy1
- platform: ads
  name: Testowy bool 2
  adsvar: P_SYSTEM.bTestowy2
- platform: ads
  name: Testowy bool 3
  adsvar: P_SYSTEM.bTestowy3
