
######################## GŁÓWNE CZUJNIKI  RUCHU ########################

- platform: ads
  name: Ruch w domu
  device_class: presence
  adsvar: GVL_Alarm.bGlobalMove
    
- platform: ads
  name: Alarm aktywny
  device_class: safety
  adsvar: GVL_Alarm.bAlarmACTIVE

- platform: ads
  name: Ruch parter
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloor0

- platform: ads
  name: Ruch pietro
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloor1

- platform: ads
  name: Ruch parter NoRoom
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloor0_NoRoom

- platform: ads
  name: Ruch pietro NoRoom
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloor1_NoRoom
        
- platform: ads
  name: Ruch Strych
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloor2

- platform: ads
  name: Ruch Zewnetrzne
  device_class: occupancy
  adsvar: GVL_Alarm.bMovmentFloorOut

- platform: ads
  name: Poranne oczekiwanie
  device_class: motion
  adsvar: GVL_Alarm.bMorningWaiting

- platform: ads
  name: Ktos jest w domu
  device_class: occupancy
  adsvar: P_ALARM.bSomeoneInHome
