
######################## SYSTEMOWE ########################

- platform: ads
  name: Ring_button
  adsvar: HomeAssistant.bDzwonek_Przycisk

- platform: ads
  name: Slonce_full
  adsvar: P_System.bSlonecznie

- platform: ads
  name: LifeBitPLC
  adsvar: P_SYSTEM.bLifeBit
    
- platform: ads
  name: LifeBitPLC HA
  adsvar: P_SYSTEM.bLifeBitHA
- platform: ads
  name: LifeBitPLC HA error
  adsvar: P_SYSTEM.bLifeBitHAerror

- platform: ads
  name: Testowy bool 1
  adsvar: P_SYSTEM.bTestowy1
- platform: ads
  name: Testowy bool 2
  adsvar: P_SYSTEM.bTestowy2
- platform: ads
  name: Testowy bool 3
  adsvar: P_SYSTEM.bTestowy3
