
######################## CZUJNIKI ZALANIA PARTER ########################

- platform: ads
  name: water_sensor_down
  adsvar: GVL_water.I_water_sensor_floor0
  device_class: safety  
- platform: ads
  name: water_sensor_down_was_detect
  adsvar: GVL_water.b_water_sensor_floor0_NOK
  device_class: safety

######################## CZUJNIKI ZALANIA PIĘTRO ########################

- platform: ads
  name: water_sensor_up
  adsvar: GVL_water.I_water_sensor_floor1
  device_class: safety
- platform: ads
  name: water_sensor_up_was_detect
  adsvar: GVL_water.b_water_sensor_floor1_NOK
  device_class: safety
    
######################## CZUJNIKI ZAWORÓW WODY PARTER ########################

- platform: ads
  name: water_valve_in_1
  adsvar: GVL_Sensors.bWater_1_CLO
  device_class: moving  
- platform: ads
  name: water_valve_in_2
  adsvar: GVL_Sensors.bWater_1_OPN
  device_class: moving  
- platform: ads
  name: water_valve_in_3
  adsvar: GVL_Sensors.bWater_2_CLO
  device_class: moving  
- platform: ads
  name: water_valve_in_4
  adsvar: GVL_Sensors.bWater_2_OPN
  device_class: moving  
- platform: ads
  name: water_valve_in_5
  adsvar: GVL_Sensors.bWater_3_CLO
  device_class: moving  
- platform: ads
  name: water_valve_in_6
  adsvar: GVL_Sensors.bWater_3_OPN
  device_class: moving  
- platform: ads
  name: water_valve_out_1
  adsvar: GVL_IO.bOutput_A4[1].bIO
  device_class: moving 
- platform: ads
  name: water_valve_out_2
  adsvar: GVL_IO.bOutput_A4[2].bIO
  device_class: moving 
- platform: ads
  name: water_valve_out_3
  adsvar: GVL_IO.bOutput_A4[3].bIO
  device_class: moving 
- platform: ads
  name: water_valve_out_4
  adsvar: GVL_IO.bOutput_A4[4].bIO
  device_class: moving 
- platform: ads
  name: water_valve_out_5
  adsvar: GVL_IO.bOutput_A4[5].bIO
  device_class: moving 
- platform: ads
  name: water_valve_out_6
  adsvar: GVL_IO.bOutput_A4[6].bIO
  device_class: moving 

######################## TRYB PRACY ZAWORÓW WODY PARTER ########################

- platform: ads
  name: water_valve_1_opening
  adsvar: P_BOILER.bValve_opening_1
  device_class: safety 
- platform: ads
  name: water_valve_2_opening
  adsvar: P_BOILER.bValve_opening_2
  device_class: safety 
- platform: ads
  name: water_valve_3_opening
  adsvar: P_BOILER.bValve_opening_3
  device_class: safety 
- platform: ads
  name: water_valve_1_closing
  adsvar: P_BOILER.bValve_closing_1
  device_class: safety 
- platform: ads
  name: water_valve_2_closing
  adsvar: P_BOILER.bValve_closing_2
  device_class: safety 
- platform: ads
  name: water_valve_3_closing
  adsvar: P_BOILER.bValve_closing_3
  device_class: safety 

######################## POMA CYRKULACJI ########################

- platform: ads
  name: Pompa cykulacji automat
  adsvar: P_BOILER.fbbadhw2p.bLd
  device_class: plug  
  
- platform: ads
  name: Zezwolenie na uruchomienie pompy
  adsvar: P_BOILER.bRelease
  
######################## PRALKA I PRALNIA ########################

- platform: ads
  name: Pralka
  adsvar: P_BOILER.bWashing
- platform: ads
  name: Pranie oczekiwanie
  adsvar: P_BOILER.bWashingWaiting


