
######################## CZUJNIKI OKIEN PARTER ######################## 

- platform: ads
  name: windows_all_p0
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_ALL_P0
    
- platform: ads
  name: window_entrance
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_ENTRENCE_HALL
- platform: ads
  name: window_bathroom_down
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_BATHROOM_DOWN
- platform: ads
  name: window_smallroom_l
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_SMALLROOM_L
- platform: ads
  name: window_smallroom_r
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_SMALLROOM_R
- platform: ads
  name: window_kitchen_l
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_KITCHEN_L
- platform: ads
  name: window_kitchen_r
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_KITCHEN_R
- platform: ads
  name: window_salon_l
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_SALON_L
- platform: ads
  name: window_salon_r
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_SALON_R
- platform: ads
  name: window_salon_taras
  device_class: door
  adsvar: GVL_Sensors.bWINDOW_GATE_SALON

######################## CZUJNIKI OKIEN PIĘTRO ########################

- platform: ads
  name: windows_all_p1
  device_class: window
  adsvar: GVL_Sensors.bWINDOW_SENSOR_ALL_P1
    
- platform: ads
  name: window_julia_l
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_JULIA_ROOM_L
- platform: ads
  name: window_julia_r
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_JULIA_ROOM_R
- platform: ads
  name: window_oliwia_l
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_OLIWIA_ROOM_L
- platform: ads
  name: window_oliwia_r
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_OLIWIA_ROOM_R
- platform: ads
  name: window_badroom_l
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_BADROOML
- platform: ads
  name: window_badroom_r
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_BADROOMR
- platform: ads
  name: window_office_l
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_OFFICE_L
- platform: ads
  name: window_office_r
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_OFFICE_R
- platform: ads
  name: window_washroom
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_WASHROOM
- platform: ads
  name: window_bathroom_up
  device_class: window
  adsvar: GVL_SENSORS.bWINDOW_SENSOR_BATHROOM_UP
