
 ############################ KAMERA ROBOROCK - ODKURZACZ ############################ 
 
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_ip
  token: !secret vacuum_token
  username: !secret vacuum_user
  password: !secret vacuum_pass
  draw: ['all']
  attributes:
  - calibration_points

 ############################### KAMERA D-LINK DCS-930LB ############################### 
 
- platform: mjpeg
  name: kamera_garaz
  mjpeg_url: !secret camera_1
  
 ############################### KAMERA D-LINK DCS-935L ############################### 
 
- platform: mjpeg
  name: kamera_parter
  mjpeg_url: !secret camera_2
